default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 20 } %>
  username: root
  password: <%= ENV.fetch("MYSQL_ROOT_PASSWORD") { 'root' } %>
  socket: /var/run/mysqld/mysqld.sock
  host: db

development:
  <<: *default
  database: <%= ENV.fetch("DEV_DATABASE_NAME") %>

test:
  <<: *default
  database: <%= ENV.fetch("TEST_DATABASE_NAME") %>